name: shop_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: ^4.3.2
  google_fonts: ^1.1.0
  intl: ^0.16.1
  http: ^0.12.2
  flutter_icons: ^1.1.0
  shared_preferences: ^0.5.10
  page_transition: ^1.1.7+6
  flutter_screenutil: ^3.2.0
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/



