name: shop_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  cached_network_image: ^2.3.2+1
  firebase_core: ^0.5.0
  country_code_picker: ^1.6.2
  path_provider: ^1.6.18
  provider: ^4.3.2
  google_fonts: ^1.1.0
  intl: ^0.16.1
  http: ^0.12.2
  flutter_icons: ^1.1.0
  image_picker: ^0.6.7+14
  shared_preferences: ^0.5.10
  page_transition: ^1.1.7+6
  flutter_screenutil: ^3.2.0
  cloud_firestore: ^0.14.3
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  hive_generator: ^0.8.2
  analyzer: 0.40.7
  build_runner: ^1.10.5
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SykaIcons
      fonts:
        - asset: assets/fonts/SykaIcons.ttf



